name: c4sport_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  lottie: ^1.2.2
  cached_network_image: ^3.2.0
  flutter_rating_bar: ^4.0.0
  get: ^4.6.1
  syncfusion_flutter_calendar: ^19.4.56
  flutter_staggered_grid_view: ^0.6.1
  amplify_flutter: ^0.4.0
  amplify_auth_cognito: ^0.4.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/loading_lottie.json
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: font/Poppins_Black.ttf
        - asset: font/Poppins_BlackItalic.ttf
        - asset: font/Poppins_Bold.ttf
        - asset: font/Poppins_BoldItalic.ttf
        - asset: font/Poppins_ExtraBold.ttf
        - asset: font/Poppins_ExtraBoldItalic.ttf
        - asset: font/Poppins_ExtraLight.ttf
        - asset: font/Poppins_ExtraLightItalic.ttf
        - asset: font/Poppins_italic.ttf
        - asset: font/Poppins_light.ttf
        - asset: font/Poppins_LightItalic.ttf
        - asset: font/Poppins_Medium.ttf
        - asset: font/Poppins_MediumItalic.ttf
        - asset: font/Poppins_Regular.ttf
        - asset: font/Poppins_SemiBold.ttf
        - asset: font/Poppins_SemiBoldItalic.ttf
        - asset: font/Poppins_Thin.ttf
        - asset: font/Poppins_ThinItalic.ttf
#          style: italic
